bucket = "bucket-with-terraform-state1"
prefix = "path/mystate"
region = "cn-hangzhou"
tablestore_endpoint = "https://terraform-hz-1.cn-hangzhou.ots.aliyuncs.com"
tablestore_table = "statelock"
endpoint = "oss-cn-hangzhou.aliyuncs.com"
# 如果oss不在企业管理主账号下需要设置相应账号的ak sk
#access_key = "xxx"
#secret_key = "xxx"